server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/belen-aedo/Entrega-2-Tingeso-main
          search-paths: config-data
  application:
    name: config-service
